global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'client-rest:8080'
          - 'server-rest:8081'
          - 'client-soap:8082'
          - 'server-soap:8083'
